app = "graph-router"
primary_region = "ewr"

[build]
image = "ghcr.io/wundergraph/cosmo/router:latest"

[env]
FEDERATED_GRAPH_NAME = "production"
LISTEN_ADDR = "0.0.0.0:3001"
# fly secrets set GRAPH_API_TOKEN=<token>

[http_service]
internal_port = 3001
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
